[package]
name = "eportfolio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
markdown = "1.0.0-alpha.20"
unchained = { package = "unchained_web", path = "../unchained" }
